const DEVICON_BASE = 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons'

const slugMap: Record<string, string> = {
  Angular: 'angularjs/angularjs-original',
  Anthropic: 'anthropic/anthropic-original',
  AWS: 'amazonwebservices/amazonwebservices-original-wordmark',
  Azure: 'azure/azure-original',
  Bitcoin: 'bitcoin/bitcoin-original',
  Blender: 'blender/blender-original',
  Bun: 'bun/bun-original',
  C: 'c/c-original',
  'C++': 'cplusplus/cplusplus-original',
  'C#': 'csharp/csharp-original',
  CSS: 'css3/css3-original',
  Clojure: 'clojure/clojure-original',
  Cloudflare: 'cloudflare/cloudflare-original',
  Dart: 'dart/dart-original',
  Debian: 'debian/debian-original',
  Deno: 'denojs/denojs-original',
  Django: 'django/django-plain',
  Docker: 'docker/docker-original',
  Electron: 'electron/electron-original',
  Elixir: 'elixir/elixir-original',
  Emacs: 'emacs/emacs-original',
  Express: 'express/express-original',
  Fedora: 'fedora/fedora-original',
  Figma: 'figma/figma-original',
  Flutter: 'flutter/flutter-original',
  GCP: 'googlecloud/googlecloud-original',
  Git: 'git/git-original',
  GitHub: 'github/github-original',
  GitLab: 'gitlab/gitlab-original',
  Go: 'go/go-original',
  Godot: 'godot/godot-original',
  Haskell: 'haskell/haskell-original',
  HTML: 'html5/html5-original',
  Java: 'java/java-original',
  JavaScript: 'javascript/javascript-original',
  Kafka: 'apachekafka/apachekafka-original',
  Kotlin: 'kotlin/kotlin-original',
  Kubernetes: 'kubernetes/kubernetes-original',
  Linux: 'linux/linux-original',
  Lua: 'lua/lua-original',
  MongoDB: 'mongodb/mongodb-original',
  MySQL: 'mysql/mysql-original',
  Netlify: 'netlify/netlify-original',
  'Next.js': 'nextjs/nextjs-original',
  Nginx: 'nginx/nginx-original',
  'Node.js': 'nodejs/nodejs-original',
  Notion: 'notion/notion-original',
  npm: 'npm/npm-original-wordmark',
  OAuth: 'oauth/oauth-original',
  OpenAI: 'openai/openai-original',
  PHP: 'php/php-original',
  Phoenix: 'phoenix/phoenix-original',
  PostgreSQL: 'postgresql/postgresql-original',
  Python: 'python/python-original',
  PyTorch: 'pytorch/pytorch-original',
  R: 'r/r-original',
  React: 'react/react-original',
  'React Native': 'react/react-original',
  Redis: 'redis/redis-original',
  Ruby: 'ruby/ruby-original',
  Rust: 'rust/rust-original',
  Scala: 'scala/scala-original',
  Spring: 'spring/spring-original',
  SQLite: 'sqlite/sqlite-original',
  Supabase: 'supabase/supabase-original',
  Swift: 'swift/swift-original',
  Tailwind: 'tailwindcss/tailwindcss-original',
  TypeScript: 'typescript/typescript-original',
  Ubuntu: 'ubuntu/ubuntu-original',
  Unity: 'unity/unity-original',
  Unreal: 'unrealengine/unrealengine-original',
  Vercel: 'vercel/vercel-original',
  Vim: 'vim/vim-original',
  Vite: 'vitejs/vitejs-original',
  'VS Code': 'vscode/vscode-original',
  WebAssembly: 'wasm/wasm-original',
  Windows: 'windows11/windows11-original',
  Zig: 'zig/zig-original',
}

export function getTechIconUrl(name: string): string | null {
  const path = slugMap[name]
  if (path) return `${DEVICON_BASE}/${path}.svg`
  return null
}
